# Generated by Django 4.2 on 2023-05-22 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categ_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('capacity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('img_src', models.SlugField(default='-')),
                ('video_src', models.SlugField(default='https://www.youtube.com/embed/KtRHV9gH83U')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255)),
                ('org_img', models.SlugField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Postitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_name', models.CharField(max_length=255)),
                ('pos_description', models.CharField(max_length=255)),
                ('pos_img', models.SlugField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1, null=True)),
                ('password', models.CharField(default='-', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('heading', models.TextField(default='-')),
                ('comment', models.TextField(default='-')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni.user')),
            ],
        ),
        migrations.CreateModel(
            name='EventsPositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni.events')),
                ('postitions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni.postitions')),
            ],
            options={
                'db_table': 'eventspostitions',
                'unique_together': {('events', 'postitions')},
            },
        ),
        migrations.CreateModel(
            name='EventsOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni.events')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni.organization')),
            ],
            options={
                'db_table': 'eventsorganization',
                'unique_together': {('events', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='EventsCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni.categories')),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni.events')),
            ],
            options={
                'db_table': 'eventscategories',
                'unique_together': {('events', 'categories')},
            },
        ),
        migrations.AddField(
            model_name='events',
            name='categories',
            field=models.ManyToManyField(null=True, through='uni.EventsCategories', to='uni.categories'),
        ),
        migrations.AddField(
            model_name='events',
            name='organizers',
            field=models.ManyToManyField(null=True, through='uni.EventsOrganization', to='uni.organization'),
        ),
        migrations.AddField(
            model_name='events',
            name='positions',
            field=models.ManyToManyField(null=True, through='uni.EventsPositions', to='uni.postitions'),
        ),
        migrations.AddField(
            model_name='events',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni.university'),
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni.user')),
            ],
        ),
    ]
