# Generated by Django 4.2 on 2023-05-23 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0002_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni.events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni.user')),
            ],
            options={
                'db_table': 'eventsuser',
                'unique_together': {('events', 'user')},
            },
        ),
    ]
