# Generated by Django 4.2 on 2023-05-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0003_eventsuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img_src',
            field=models.SlugField(default='-'),
        ),
    ]
