# Generated by Django 4.2 on 2023-05-23 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0004_user_img_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='uni.postitions'),
        ),
    ]
