# Generated by Django 4.2 on 2023-05-23 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0005_alter_volunteer_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='positions',
        ),
        migrations.AddField(
            model_name='postitions',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uni.events'),
        ),
        migrations.DeleteModel(
            name='EventsPositions',
        ),
    ]
