# Generated by Django 4.2 on 2023-05-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0009_categories_categ_apr'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='categ_desc',
            field=models.TextField(default='-'),
        ),
    ]
