# Generated by Django 4.2 on 2023-05-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0012_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
