# Generated by Django 4.2 on 2023-05-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0015_alter_user_university'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='heading',
            new_name='comment_title',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Success'), ('F', 'Fail')], default='P', max_length=1),
        ),
    ]
