# Generated by Django 4.2 on 2023-05-25 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0016_rename_heading_volunteer_comment_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='comment_title',
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_title', models.TextField(default='-')),
                ('comment', models.TextField(default='-')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='uni.postitions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni.user')),
            ],
        ),
    ]
