# Generated by Django 4.2 on 2023-05-25 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0017_remove_volunteer_comment_title_testimonials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='user',
        ),
        migrations.AddField(
            model_name='testimonials',
            name='volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='uni.volunteer'),
        ),
    ]
