# Generated by Django 4.2 on 2023-05-25 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0018_remove_testimonials_user_testimonials_volunteer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='position',
        ),
    ]
